---
title: "Decomposition of Time Series"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Generally, we can categorize patterns in time series data into the following two categories:
 
* **Structural patterns -** also known as the series components. There are three main components:
    * trend - the series growth overtime
    * cycle - repeated events over time that are not equally spaced
    * seasonal - repeated events over time that are equally spaced
* **Non-structural patterns -** also known as the irregular components, which is basically any pattern on the series that is not represented by the structural patterns. An example of such a pattern could be repeated events that are not seasonal (e.g., Easter or the Chinese New Year are both occurred every year, but the date is changing from year to year)

Those patterns are either exists or not (e.g., a series may have a trend or not). We can express those components using the following notation for additive structure:

$$Y_t=T_t + C_t + S_t + I_t, $$

And for multiplicative structure:

$$Y_t=T_t \times C_t \times S_t \times I_t $$


For simplicity reasons, we will joined the cycle component into the trend, and rewrite the series components notation for additive structure:

$$Y_t=T_t + S_t + I_t, $$ 
And for multiplicative structure:

$$Y_t=T_t \times S_t \times I_t $$


In this section, we will focus on decomposition methods of time series to its components - the trend, seasonal, and irregular.

### Classical Decomposition

The classical decomposition (or by its full name - classical seasonal decomposition by moving average)